import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sistema de Agendamento",
  description: "Generated by Icaro de Oliveira and Jefferson Simplicito",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
        <body className="dark">
          <main className="grid h-screen w-screen place-content-center">
            {children}
          </main>
        </body>    
      </html>
  );
}
